title: Free Shitter Party
logo: assets/img/logo.png
description: Keep your laws off my poop!
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
